// <auto-generated />
namespace Datalayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModelsUpdateAnnotations1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelsUpdateAnnotations1));
        
        string IMigrationMetadata.Id
        {
            get { return "201701301539183_ModelsUpdateAnnotations1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
